version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/db:/docker-entrypoint-initdb.d
      - ../logs/mysql:/var/log/mysql
      - ../../provisioning/ansible/roles/web-bootstrap/files/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../../provisioning/ansible/roles/web-bootstrap/files/slow-mysqld.cnf:/etc/mysql/conf.d/slowquery.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isuumo
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    ports:
      - "3306:3306"

  api-server:
    build: ../go
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://mysql:3306
    volumes:
      - ../mysql/db:/go/src/mysql/db
      - ../fixture:/go/src/fixture
    environment:
      MYSQL_DBNAME: isuumo
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
      MYSQL_HOST: mysql
      SERVER_PORT: 1323
      DD_AGENT_HOST: datadog
      DD_TRACE_AGENT_PORT: "8126"
    ports:
      - "1323:1323"
    depends_on:
      - mysql
    links:
      - datadog
    command: /go/src/isuumo/isuumo

  frontend:
    build: ../frontend
    volumes:
      - ../nginx/out:/frontend/out

  nginx:
    build: ../nginx
    volumes:
      - ../../provisioning/ansible/roles/web-bootstrap/files/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ../logs/nginx:/var/log/nginx
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/out:/www/data
    ports:
      - "8080:80"
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - http://api-server:1323/api/estate/search/condition
    environment:
      API_SERVER: api-server
    depends_on:
      - api-server
    links:
      - datadog
    command: >
      /bin/sh -c
      "envsubst '
      $$API_SERVER
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=11111111111111111111111111111111
      - DD_SITE=datadoghq.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
